import type { ModuleId } from "./modules";
import type { ProviderType } from "../schemas/config";
import type { DashboardLayoutItem } from "../schemas/config";

export interface ProviderPreset {
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly providerType: ProviderType;
  readonly enabledModules: readonly ModuleId[];
  readonly defaultTrackerPreset: string;
  readonly dashboardLayout: DashboardLayoutItem[];
  readonly clientOverviewLayout: DashboardLayoutItem[];
  readonly defaultAssessments: readonly string[];
}

function layoutItems(
  widgets: Array<{ id: string; column?: "main" | "sidebar" }>
): DashboardLayoutItem[] {
  return widgets.map((w, i) => ({
    widgetId: w.id,
    visible: true,
    column: w.column ?? "main",
    order: i,
    settings: {},
  }));
}

const DEFAULT_CLIENT_OVERVIEW = layoutItems([
  { id: "client_demographics" },
  { id: "client_sessions" },
  { id: "client_homework" },
  { id: "client_trackers" },
  { id: "client_assessments" },
  { id: "client_progress" },
  { id: "client_journal", column: "sidebar" },
  { id: "client_alerts", column: "sidebar" },
  { id: "client_notes", column: "sidebar" },
  { id: "client_quick_actions", column: "sidebar" },
]);

export const PROVIDER_PRESETS: Record<string, ProviderPreset> = {
  THERAPIST_CBT: {
    id: "THERAPIST_CBT",
    label: "Therapist — CBT",
    description: "Cognitive Behavioral Therapy focus with thought records, homework, and structured skill-building",
    providerType: "THERAPIST",
    enabledModules: [
      "daily_tracker", "homework", "journal", "assessments",
      "strategy_cards", "program_modules", "pre_visit_summary",
      "secure_messaging", "rtm_billing",
    ],
    defaultTrackerPreset: "cbt_standard",
    dashboardLayout: layoutItems([
      { id: "stat_active_clients" },
      { id: "stat_sessions_today" },
      { id: "stat_homework_rate" },
      { id: "stat_overdue_count" },
      { id: "todays_sessions" },
      { id: "checkin_alerts" },
      { id: "overdue_homework" },
      { id: "tracker_summary" },
      { id: "homework_status" },
      { id: "assessment_scores" },
      { id: "program_progress" },
      { id: "pre_visit" },
      { id: "recent_submissions", column: "sidebar" },
      { id: "journal_activity", column: "sidebar" },
      { id: "recent_messages", column: "sidebar" },
      { id: "quick_actions", column: "sidebar" },
      { id: "rtm_overview" },
    ]),
    clientOverviewLayout: DEFAULT_CLIENT_OVERVIEW,
    defaultAssessments: ["ASRS", "PHQ-9", "GAD-7"],
  },
  THERAPIST_DBT: {
    id: "THERAPIST_DBT",
    label: "Therapist — DBT",
    description: "Dialectical Behavior Therapy focus with emotion regulation tracking and distress tolerance skills",
    providerType: "THERAPIST",
    enabledModules: [
      "daily_tracker", "homework", "journal", "assessments",
      "strategy_cards", "program_modules", "pre_visit_summary",
      "secure_messaging", "rtm_billing",
    ],
    defaultTrackerPreset: "dbt_diary_card",
    dashboardLayout: layoutItems([
      { id: "stat_active_clients" },
      { id: "stat_sessions_today" },
      { id: "stat_homework_rate" },
      { id: "stat_overdue_count" },
      { id: "todays_sessions" },
      { id: "checkin_alerts" },
      { id: "overdue_homework" },
      { id: "tracker_summary" },
      { id: "homework_status" },
      { id: "assessment_scores" },
      { id: "program_progress" },
      { id: "pre_visit" },
      { id: "recent_submissions", column: "sidebar" },
      { id: "journal_activity", column: "sidebar" },
      { id: "recent_messages", column: "sidebar" },
      { id: "quick_actions", column: "sidebar" },
      { id: "rtm_overview" },
    ]),
    clientOverviewLayout: DEFAULT_CLIENT_OVERVIEW,
    defaultAssessments: ["ASRS", "PHQ-9", "DERS-18"],
  },
  THERAPIST_TRAUMA: {
    id: "THERAPIST_TRAUMA",
    label: "Therapist — Trauma",
    description: "Trauma-focused therapy with PTSD symptom tracking and safety planning",
    providerType: "THERAPIST",
    enabledModules: [
      "daily_tracker", "homework", "journal", "assessments",
      "strategy_cards", "audio_resources", "program_modules",
      "pre_visit_summary", "secure_messaging", "rtm_billing",
    ],
    defaultTrackerPreset: "trauma_focused",
    dashboardLayout: layoutItems([
      { id: "stat_active_clients" },
      { id: "stat_sessions_today" },
      { id: "stat_homework_rate" },
      { id: "stat_overdue_count" },
      { id: "todays_sessions" },
      { id: "checkin_alerts" },
      { id: "overdue_homework" },
      { id: "tracker_summary" },
      { id: "homework_status" },
      { id: "assessment_scores" },
      { id: "program_progress" },
      { id: "pre_visit" },
      { id: "recent_submissions", column: "sidebar" },
      { id: "journal_activity", column: "sidebar" },
      { id: "recent_messages", column: "sidebar" },
      { id: "quick_actions", column: "sidebar" },
      { id: "rtm_overview" },
    ]),
    clientOverviewLayout: DEFAULT_CLIENT_OVERVIEW,
    defaultAssessments: ["ASRS", "PCL-5", "PHQ-9", "GAD-7"],
  },
  THERAPIST_OCD: {
    id: "THERAPIST_OCD",
    label: "Therapist — OCD",
    description: "OCD-focused with exposure hierarchy tracking and compulsion monitoring",
    providerType: "THERAPIST",
    enabledModules: [
      "daily_tracker", "homework", "journal", "assessments",
      "strategy_cards", "program_modules", "pre_visit_summary",
      "secure_messaging", "rtm_billing",
    ],
    defaultTrackerPreset: "ocd_erp",
    dashboardLayout: layoutItems([
      { id: "stat_active_clients" },
      { id: "stat_sessions_today" },
      { id: "stat_homework_rate" },
      { id: "stat_overdue_count" },
      { id: "todays_sessions" },
      { id: "checkin_alerts" },
      { id: "overdue_homework" },
      { id: "tracker_summary" },
      { id: "homework_status" },
      { id: "assessment_scores" },
      { id: "program_progress" },
      { id: "pre_visit" },
      { id: "recent_submissions", column: "sidebar" },
      { id: "journal_activity", column: "sidebar" },
      { id: "recent_messages", column: "sidebar" },
      { id: "quick_actions", column: "sidebar" },
      { id: "rtm_overview" },
    ]),
    clientOverviewLayout: DEFAULT_CLIENT_OVERVIEW,
    defaultAssessments: ["ASRS", "Y-BOCS", "PHQ-9", "GAD-7"],
  },
  THERAPIST_SUBSTANCE: {
    id: "THERAPIST_SUBSTANCE",
    label: "Therapist — Substance Use",
    description: "Substance use treatment with craving tracking and relapse prevention",
    providerType: "THERAPIST",
    enabledModules: [
      "daily_tracker", "homework", "journal", "assessments",
      "strategy_cards", "program_modules", "pre_visit_summary",
      "secure_messaging", "rtm_billing",
    ],
    defaultTrackerPreset: "substance_use",
    dashboardLayout: layoutItems([
      { id: "stat_active_clients" },
      { id: "stat_sessions_today" },
      { id: "stat_homework_rate" },
      { id: "stat_overdue_count" },
      { id: "todays_sessions" },
      { id: "checkin_alerts" },
      { id: "overdue_homework" },
      { id: "tracker_summary" },
      { id: "homework_status" },
      { id: "assessment_scores" },
      { id: "program_progress" },
      { id: "pre_visit" },
      { id: "recent_submissions", column: "sidebar" },
      { id: "journal_activity", column: "sidebar" },
      { id: "recent_messages", column: "sidebar" },
      { id: "quick_actions", column: "sidebar" },
      { id: "rtm_overview" },
    ]),
    clientOverviewLayout: DEFAULT_CLIENT_OVERVIEW,
    defaultAssessments: ["ASRS", "AUDIT", "DAST-10", "PHQ-9"],
  },
  THERAPIST_INSOMNIA: {
    id: "THERAPIST_INSOMNIA",
    label: "Therapist — Insomnia (CBT-I)",
    description: "Insomnia-focused CBT with sleep diary and sleep hygiene tracking",
    providerType: "THERAPIST",
    enabledModules: [
      "daily_tracker", "homework", "journal", "assessments",
      "strategy_cards", "program_modules", "pre_visit_summary",
      "secure_messaging", "rtm_billing",
    ],
    defaultTrackerPreset: "cbti_sleep_diary",
    dashboardLayout: layoutItems([
      { id: "stat_active_clients" },
      { id: "stat_sessions_today" },
      { id: "stat_homework_rate" },
      { id: "stat_overdue_count" },
      { id: "todays_sessions" },
      { id: "checkin_alerts" },
      { id: "overdue_homework" },
      { id: "tracker_summary" },
      { id: "homework_status" },
      { id: "assessment_scores" },
      { id: "program_progress" },
      { id: "pre_visit" },
      { id: "recent_submissions", column: "sidebar" },
      { id: "journal_activity", column: "sidebar" },
      { id: "recent_messages", column: "sidebar" },
      { id: "quick_actions", column: "sidebar" },
      { id: "rtm_overview" },
    ]),
    clientOverviewLayout: DEFAULT_CLIENT_OVERVIEW,
    defaultAssessments: ["ASRS", "ISI", "PHQ-9", "GAD-7"],
  },
  PSYCHIATRIST_MED_MGMT: {
    id: "PSYCHIATRIST_MED_MGMT",
    label: "Psychiatrist — Medication Management",
    description: "Medication-focused with adherence tracking, side effects monitoring, and outcome assessments",
    providerType: "PSYCHIATRIST",
    enabledModules: [
      "daily_tracker", "assessments", "medication_tracker",
      "side_effects", "pre_visit_summary", "secure_messaging",
      "rtm_billing",
    ],
    defaultTrackerPreset: "med_management",
    dashboardLayout: layoutItems([
      { id: "stat_active_clients" },
      { id: "stat_sessions_today" },
      { id: "todays_sessions" },
      { id: "checkin_alerts" },
      { id: "tracker_summary" },
      { id: "medication_adherence" },
      { id: "side_effects_report" },
      { id: "assessment_scores" },
      { id: "pre_visit" },
      { id: "recent_messages", column: "sidebar" },
      { id: "quick_actions", column: "sidebar" },
      { id: "rtm_overview" },
    ]),
    clientOverviewLayout: DEFAULT_CLIENT_OVERVIEW,
    defaultAssessments: ["ASRS", "PHQ-9", "GAD-7"],
  },
  PSYCHIATRIST_INTEGRATED: {
    id: "PSYCHIATRIST_INTEGRATED",
    label: "Psychiatrist — Integrated",
    description: "Combined medication management and therapy with full monitoring suite",
    providerType: "PSYCHIATRIST",
    enabledModules: [
      "daily_tracker", "homework", "journal", "assessments",
      "medication_tracker", "side_effects", "strategy_cards",
      "program_modules", "pre_visit_summary", "secure_messaging",
      "rtm_billing",
    ],
    defaultTrackerPreset: "integrated_psych",
    dashboardLayout: layoutItems([
      { id: "stat_active_clients" },
      { id: "stat_sessions_today" },
      { id: "stat_homework_rate" },
      { id: "stat_overdue_count" },
      { id: "todays_sessions" },
      { id: "checkin_alerts" },
      { id: "overdue_homework" },
      { id: "tracker_summary" },
      { id: "medication_adherence" },
      { id: "side_effects_report" },
      { id: "homework_status" },
      { id: "assessment_scores" },
      { id: "program_progress" },
      { id: "pre_visit" },
      { id: "recent_submissions", column: "sidebar" },
      { id: "journal_activity", column: "sidebar" },
      { id: "recent_messages", column: "sidebar" },
      { id: "quick_actions", column: "sidebar" },
      { id: "rtm_overview" },
    ]),
    clientOverviewLayout: DEFAULT_CLIENT_OVERVIEW,
    defaultAssessments: ["ASRS", "PHQ-9", "GAD-7"],
  },
  PSYCH_NP: {
    id: "PSYCH_NP",
    label: "Psychiatric Nurse Practitioner",
    description: "Medication management with monitoring, similar to psychiatrist med management",
    providerType: "PSYCH_NP",
    enabledModules: [
      "daily_tracker", "assessments", "medication_tracker",
      "side_effects", "pre_visit_summary", "secure_messaging",
      "rtm_billing",
    ],
    defaultTrackerPreset: "med_management",
    dashboardLayout: layoutItems([
      { id: "stat_active_clients" },
      { id: "stat_sessions_today" },
      { id: "todays_sessions" },
      { id: "checkin_alerts" },
      { id: "tracker_summary" },
      { id: "medication_adherence" },
      { id: "side_effects_report" },
      { id: "assessment_scores" },
      { id: "pre_visit" },
      { id: "recent_messages", column: "sidebar" },
      { id: "quick_actions", column: "sidebar" },
      { id: "rtm_overview" },
    ]),
    clientOverviewLayout: DEFAULT_CLIENT_OVERVIEW,
    defaultAssessments: ["ASRS", "PHQ-9", "GAD-7"],
  },
  COACH_ADHD: {
    id: "COACH_ADHD",
    label: "ADHD Coach",
    description: "Executive function coaching with productivity tools and habit tracking",
    providerType: "COACH",
    enabledModules: [
      "daily_tracker", "journal", "strategy_cards", "todo_list",
      "calendar", "secure_messaging",
    ],
    defaultTrackerPreset: "coaching_exec_function",
    dashboardLayout: layoutItems([
      { id: "stat_active_clients" },
      { id: "stat_sessions_today" },
      { id: "todays_sessions" },
      { id: "checkin_alerts" },
      { id: "tracker_summary" },
      { id: "journal_activity", column: "sidebar" },
      { id: "todo_progress", column: "sidebar" },
      { id: "recent_messages", column: "sidebar" },
      { id: "quick_actions", column: "sidebar" },
    ]),
    clientOverviewLayout: DEFAULT_CLIENT_OVERVIEW,
    defaultAssessments: ["ASRS"],
  },
  GENERAL: {
    id: "GENERAL",
    label: "General",
    description: "Balanced default configuration suitable for any provider type",
    providerType: "OTHER",
    enabledModules: [
      "daily_tracker", "homework", "journal", "assessments",
      "strategy_cards", "program_modules", "pre_visit_summary",
      "secure_messaging",
    ],
    defaultTrackerPreset: "general",
    dashboardLayout: layoutItems([
      { id: "stat_active_clients" },
      { id: "stat_sessions_today" },
      { id: "stat_homework_rate" },
      { id: "stat_overdue_count" },
      { id: "todays_sessions" },
      { id: "checkin_alerts" },
      { id: "overdue_homework" },
      { id: "tracker_summary" },
      { id: "homework_status" },
      { id: "assessment_scores" },
      { id: "program_progress" },
      { id: "pre_visit" },
      { id: "recent_submissions", column: "sidebar" },
      { id: "journal_activity", column: "sidebar" },
      { id: "recent_messages", column: "sidebar" },
      { id: "quick_actions", column: "sidebar" },
    ]),
    clientOverviewLayout: DEFAULT_CLIENT_OVERVIEW,
    defaultAssessments: ["ASRS", "PHQ-9", "GAD-7"],
  },
};

export type ProviderPresetId = keyof typeof PROVIDER_PRESETS;

export function getPresetsForProviderType(
  providerType: ProviderType
): ProviderPreset[] {
  return Object.values(PROVIDER_PRESETS).filter(
    (preset) => preset.providerType === providerType
  );
}
