export const appointmentStrings = {
  navLabel: "Calendar",
  pageTitle: "Calendar",
  browserTitle: "Calendar — Steady",
  viewDay: "Day",
  viewWeek: "Week",
  viewMonth: "Month",
  today: "Today",
  prev: "Previous",
  next: "Next",
  filtersButton: "Filters",
  filtersLocation: "Location",
  filtersStatus: "Status",
  filtersClinician: "Clinician",
  filtersClear: "Clear filters",
  filtersApply: "Apply",
  scheduleBtn: "Schedule appointment",
  scheduleFirstBtn: "Schedule your first appointment",
  newAppointmentBtn: "+ New appointment",
  emptyWeek: "No appointments this week",
  emptyDay: (day: string) => `Nothing scheduled for ${day}`,
  emptyFiltered: "No appointments match these filters",
  loadError: "Couldn't load your calendar.",
  retry: "Retry",
  modalCreateTitle: "Schedule appointment",
  modalEditTitle: "Edit appointment",
  modalClient: "Client",
  modalClientPlaceholder: "Search by name or email",
  modalClientHint: "Type at least 2 characters",
  modalClientNoMatches: "No matches",
  modalClientAddNew: (q: string) => `+ Add new client "${q}"`,
  modalServiceCode: "Service code",
  modalLocation: "Location",
  modalWhen: "When",
  modalAppointmentType: "Appointment type",
  modalTypeIndividual: "Individual",
  modalTypeCouple: "Couple",
  modalInternalNoteLabel: "Internal note (only you see this)",
  modalInternalNotePlaceholder: "e.g. bring insurance card, check SOAP notes from last visit",
  modalCancelBtn: "Cancel",
  modalScheduleBtn: "Schedule appointment",
  modalSaveBtn: "Save changes",
  modalDeleteBtn: "Delete",
  modalSavingBtn: "Saving…",
  modalDiscardConfirmTitle: "Discard changes?",
  modalDiscardKeep: "Keep editing",
  modalDiscardDiscard: "Discard",
  modalDeleteConfirmTitle: "Permanently delete this appointment?",
  modalDeleteConfirmBody:
    "This is for mistakes only — use 'Cancel' status for real cancellations.",
  modalDeleteConfirmYes: "Yes, delete",
  modalDeleteConfirmNo: "Keep it",
  modalTerminalBanner:
    "This appointment is completed. Only the internal note can be edited.",
  modalConflictBanner: (n: number) =>
    `This overlaps with ${n} existing appointment${n === 1 ? "" : "s"}.`,
  modalConflictView: "View",
  modalConflictKeep: "Keep",
  modalConflictUndo: "Undo",
  statusChangeTitle: "Change status",
  statusScheduled: "Scheduled",
  statusAttended: "Attended",
  statusNoShow: "No-show",
  statusLateCanceled: "Late canceled",
  statusClientCanceled: "Client canceled",
  statusClinicianCanceled: "You canceled",
  statusReasonLabel: "Reason (optional)",
  statusReasonPlaceholder: "Optional — visible only to you and your practice",
  statusBackBtn: "Back",
  statusConfirmBtn: "Confirm",
  validationEndBeforeStart: "End time must be after start time",
  validationMissingClient: "Pick a client to continue",
  errorCrossTenant: "We couldn't find that appointment.",
  errorTerminalSchedule:
    "Can't reschedule a completed appointment. Undo status first, or edit only the note.",
  errorRateLimitSearch: "Too many searches, wait a moment.",
  errorSessionExpired: "Your session expired. Sign in again to continue.",
  errorGeneric: "Something went wrong",
  toastCreated: "Appointment scheduled",
  toastCreatedWithConflicts: "Scheduled — check conflicts",
  toastUpdated: "Appointment updated",
  toastStatusChanged: (label: string) => `Marked ${label.toLowerCase()}`,
  toastDeleted: "Appointment deleted",
  toastUndo: "Undo",
  addClientPanelTitle: "Add new client",
  addClientFirstName: "First name",
  addClientLastName: "Last name",
  addClientEmail: "Email",
  addClientSubmit: "Create client",
  addClientCancel: "Cancel",
  addClientEmailExists: "This email is already a client.",
};

export type AppointmentStrings = typeof appointmentStrings;
